language: swift
osx_image: xcode9
os: osx
xcode_project: Log.xcodeproj

branches:
  only:
    - master
before_install:
  - brew update
  - brew install swiftlint || true
  - brew install carthage
  - carthage update --platform iOS
  
